#Ltot
Ltot = L + Lp + LpA + LpP + LpAK + LpAP + 2 * LpAKL +  2 * LpAPLp + AKL + APLp + LK
#dL
du[1] = AKL*kb3 + APLp*kcat7 + kb3*LpAKL + kcat7*LpAPLp + kcat7*LpP - A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + (AKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) + (LpAKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) - (AK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2* LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K - (DF*LpAK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2* LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K
#dK
du[2] = -(A*K*ka3) + AK*kb3 + AKL*kb3 - K*ka3*LpA + kb3*LpAK + kb3*LpAKL - A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)
#dP
du[3] = AP*kb4 + kb4*LpAP + kb7*LpP + kcat7*LpP - A*ka4*P - ka7*Lp*P - ka4*LpA*P
#dA
du[4] = -(A*K*ka3) + AK*kb3 + AKL*kb3 + AP*kb4 + APLp*kb4 - A*ka2*Lp + kb2*LpA - A*ka4*LpP - A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - A*ka4*P 
#dLp
du[5] = APLp*kb7 + AKL*kcat1 - A*ka2*Lp - AK*ka2*Lp - AP*ka2*Lp - AKL*DF*ka2*Lp - APLp*DF*ka2*Lp - AP*ka7*Lp + kb2*LpA + kb2*LpAK + kb2*LpAKL + kcat1*LpAKL + kb2*LpAP - DF*ka7*Lp*LpAP + kb2*LpAPLp + kb7*LpAPLp + kb7*LpP + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - ka7*Lp*P 
#dLpA
du[6] = A*ka2*Lp - K*ka3*LpA - kb2*LpA + kb3*LpAK + kb3*LpAKL + kb4*LpAP + kb4*LpAPLp - DF*ka4*LpA*LpP - DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - ka4*LpA*P
#dLK 
du[7] = 0
#dLpP
du[8] = APLp*kb4 + kb4*LpAPLp - A*ka4*LpP - kb7*LpP - kcat7*LpP - DF*ka4*LpA*LpP + ka7*Lp*P
#dLpAK
du[9] = AK*ka2*Lp + K*ka3*LpA - kb2*LpAK - kb3*LpAK + kcat1*LpAKL + (LpAKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) - (DF*LpAK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2* LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K 
#dLpAP
du[10] = AP*ka2*Lp - kb2*LpAP - kb4*LpAP - DF*ka7*Lp*LpAP + kb7*LpAPLp + kcat7*LpAPLp + ka4*LpA*P
#dLpAKL
du[11] = AKL*DF*ka2*Lp - kb2*LpAKL - kb3*LpAKL - kcat1*LpAKL + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - (LpAKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) + (DF*LpAK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2* LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K
#dLpAPLp
du[12] = APLp*DF*ka2*Lp + DF*ka7*Lp*LpAP - kb2*LpAPLp - kb4*LpAPLp - kb7*LpAPLp - kcat7*LpAPLp + DF*ka4*LpA*LpP
#dAK
du[13] = A*K*ka3 - AK*kb3 + AKL*kcat1 - AK*ka2*Lp + kb2*LpAK + (AKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) - (AK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2* LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K
#dAP
du[14] = -(AP*kb4) + APLp*kb7 + APLp*kcat7 - AP*ka2*Lp - AP*ka7*Lp + kb2*LpAP + A*ka4*P
#dAKL
du[15] = -(AKL*kb3) - AKL*kcat1 - AKL*DF*ka2*Lp + kb2*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) - (AKL*(-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/(K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)) + (AK*(-(AKL*kb3) - kb3*LpAKL + A*ka3*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*LpA*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + ((-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)* (-(AKL*kb3*Km1) - K*kcat1*L - kb3*Km1*LpAKL + A*ka3*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + kcat1*Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot) + DF*ka3*Km1*LpA* (-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot)))/ (K*L - Km1*(-AKL - APLp - L - Lp - LpA - LpAK - 2*LpAKL - LpAP - 2*LpAPLp - LpP + Ltot))))/K
#dAPLp
du[16] = -(APLp*kb4) - APLp*kb7 - APLp*kcat7 - APLp*DF*ka2*Lp + AP*ka7*Lp + kb2*LpAPLp + A*ka4*LpP
