using DifferentialEquations
#Full reaction model with ka1 and kb1 eliminated using dLK = 0 and dLpAKL = 0
function eliminationSystem!(du, u, p, t)
     #Parameter and concetrations, concentrations, and differentials definitions
     Km1, kcat1, ka2, kb2, ka3, kb3, ka4, kb4, ka7, kb7, kcat7, DF = p
     L, K , P , A, Lp,  LpA, LK, LpP, LpAK, LpAP , LpAKL , LpAPLp , AK , AP , AKL , APLp = u
    
     #dL = du[1] will have to be found from these constraints...
     #dL, dK, dAK, dAKL, dLK, dLpAK, dLpAKL are all from Mathematica
    #dL FROM FIRST MATHEMATICA CONSTRAINT; SEE BELOW THE function
    dL = (AKL^2*kb3*Km1 - AK*AKL*kb3*L - AKL*K*kb3*L + AKL*K*kcat1*L - APLp*K*kcat7*L - A*AKL*ka3*Km1*LK + AKL*kb3*Km1*LK - AKL*kcat1*Km1*LK + APLp*kcat7*Km1*LK + A*AK*ka3*L*LK + A*K*ka3*L*LK + K*kcat1*L*LK - A*ka3*Km1*LK^2 - kcat1*Km1*LK^2 - AKL*DF*ka3*Km1*LK*LpA + AK*DF*ka3*L*LK*LpA + DF*K*ka3*L*LK*LpA - DF*ka3*Km1*LK^2*LpA - AKL*DF*kb3*L*LpAK + A*DF*ka3*L*LK*LpAK + DF^2*ka3*L*LK*LpA*LpAK + 2*AKL*kb3*Km1*LpAKL - AK*kb3*L*LpAKL - K*kb3*L*LpAKL + K*kcat1*L*LpAKL - A*ka3*Km1*LK*LpAKL + kb3*Km1*LK*LpAKL - kcat1*Km1*LK*LpAKL - DF*ka3*Km1*LK*LpA*LpAKL - DF*kb3*L*LpAK*LpAKL + kb3*Km1*LpAKL^2 - K*kcat7*L*LpAPLp + kcat7*Km1*LK*LpAPLp - K*kcat7*L*LpP + kcat7*Km1*LK*LpP ) / (-(K*L) + Km1*LK)
    #dK 
    du[2] = -(A*K*ka3) + AK*kb3 + AKL*kb3 - A*ka3*LK - K*ka3*LpA - DF*ka3*LK*LpA + kb3*LpAK + kb3*LpAKL 
    #dP 
    du[3] = kb4*AP + kb4*LpAP + kb7*LpP + kcat7*LpP - ka4*A*P - ka7*Lp*P - ka4*LpA*P 
    #dA
    du[4] = kb2*LpA + kb3*AK + kb3*AKL + kb4*AP + kb4*APLp - ka2*A*Lp - ka3*A*K - ka3*A*LK - ka4*A*LpP - ka4*A*P 
    #dLp
    du[5] = kb7*APLp + kcat1*AKL + kcat1*LK + kb2*LpA + kb2*LpAK + kb2*LpAKL + kb2*LpAP + kcat1*LpAKL + kb2*LpAPLp + kb7*LpAPLp + kb7*LpP - ka2*A*Lp - ka2*AK*Lp - ka2*AP*Lp - ka7*AP*Lp - ka7*Lp*P - ka2*DF*AKL*Lp - ka2*DF*APLp*Lp - ka7*DF*Lp*LpAP 
    #dLpA
    du[6] = kb3*LpAK + kb3*LpAKL + kb4*LpAP + kb4*LpAPLp + ka2*A*Lp - kb2*LpA - ka3*K*LpA - ka4*LpA*P - ka3*DF*LK*LpA - ka4*DF*LpA*LpP 
    #dLK (MM assumption)
    du[7] = 0
    #dLpP
    du[8] = kb4*APLp + kb4*LpAPLp + ka7*Lp*P - kb7*LpP - kcat7*LpP - ka4*A*LpP - ka4*DF*LpA*LpP 
    #dLpAK
    du[9] = AK*ka2*Lp + AKL*DF*ka2*Lp + K*ka3*LpA + DF*ka3*LK*LpA - kb2*LpAK - kb3*LpAK - kb2*LpAKL - kb3*LpAKL 
    #dLpAP 
    du[10] = kb7*LpAPLp + kcat7*LpAPLp + ka2*AP*Lp + ka4*LpA*P - kb2*LpAP - kb4*LpAP - ka7*DF*Lp*LpAP 
    #dLpAKL (MM Assumption)
    du[11] = 0
    #dLpAPLp
    du[12] = ka2*DF*APLp*Lp + ka7*DF*Lp*LpAP + ka4*DF*LpA*LpP - kb2*LpAPLp - kb4*LpAPLp - kb7*LpAPLp - kcat7*LpAPLp 
    #dAK
    du[13] = dL + A*K*ka3 - AK*kb3 - AKL*kb3 + AKL*kcat1 - APLp*kcat7 + A*ka3*LK + kcat1*LK - AK*ka2*Lp - AKL*DF*ka2*Lp + kb2*LpAK + kb2*LpAKL + kcat1*LpAKL - kcat7*LpAPLp - kcat7*LpP 
    #dAP
    du[14] = kb2*LpAP + kb7*APLp + kcat7*APLp + ka4*A*P - kb4*AP - ka2*AP*Lp - ka7*AP*Lp 
    #dAKL
    du[15] = -dL - AKL*kcat1 + APLp*kcat7 - kcat1*LK - kcat1*LpAKL + kcat7*LpAPLp + kcat7*LpP 
    #dAPLp
    du[16] = kb2*LpAPLp + ka7*AP*Lp + ka4*A*LpP - kb4*APLp - kb7*APLp - kcat7*APLp - ka2*DF*APLp*Lp
    nothing
end
#=
    THESE CONSTRAINTS WERE GENERATED BY MATHEMATICA. I USED THE FIRST EQUATION AS MY FORMULA FOR dL BY DIVIDING BY THE COEFFICIENTS
    dL*(-(K*L) + Km1*LK) = AKL^2*kb3*Km1 - AK*AKL*kb3*L - AKL*K*kb3*L + AKL*K*kcat1*L - APLp*K*kcat7*L - A*AKL*ka3*Km1*LK + AKL*kb3*Km1*LK - AKL*kcat1*Km1*LK + APLp*kcat7*Km1*LK + A*AK*ka3*L*LK + A*K*ka3*L*LK + K*kcat1*L*LK - A*ka3*Km1*LK^2 - kcat1*Km1*LK^2 - AKL*DF*ka3*Km1*LK*LpA + AK*DF*ka3*L*LK*LpA + DF*K*ka3*L*LK*LpA - DF*ka3*Km1*LK^2*LpA - AKL*DF*kb3*L*LpAK + A*DF*ka3*L*LK*LpAK + DF^2*ka3*L*LK*LpA*LpAK + 2*AKL*kb3*Km1*LpAKL - AK*kb3*L*LpAKL - K*kb3*L*LpAKL + K*kcat1*L*LpAKL - A*ka3*Km1*LK*LpAKL + kb3*Km1*LK*LpAKL - kcat1*Km1*LK*LpAKL - DF*ka3*Km1*LK*LpA*LpAKL - DF*kb3*L*LpAK*LpAKL + kb3*Km1*LpAKL^2 - K*kcat7*L*LpAPLp + kcat7*Km1*LK*LpAPLp - K*kcat7*L*LpP + kcat7*Km1*LK*LpP \
    dL*(-(DF*LK*LpAK) + K*LpAKL) = AKL^2*DF*K*ka2*Lp - AK*AKL*DF*ka2*LK*Lp + AKL*DF*K*ka3*LK*LpA - AK*DF*ka3*LK^2*LpA - AKL^2*DF*kb3*LpAK + A*AKL*DF*ka3*LK*LpAK - AKL*DF*kb3*LK*LpAK + AKL*DF*kcat1*LK*LpAK - APLp*DF*kcat7*LK*LpAK + A*DF*ka3*LK^2*LpAK + DF*kcat1*LK^2*LpAK - AKL*DF^2*ka2*LK*Lp*LpAK + AKL*DF^2*ka3*LK*LpA*LpAK - AKL*K*kb2*LpAKL + AK*AKL*kb3*LpAKL - AKL*K*kcat1*LpAKL + APLp*K*kcat7*LpAKL - A*AK*ka3*LK*LpAKL - A*K*ka3*LK*LpAKL + AK*kb2*LK*LpAKL + AK*kb3*LK*LpAKL - K*kcat1*LK*LpAKL + AKL*DF*K*ka2*Lp*LpAKL - AK*DF*ka3*LK*LpA*LpAKL - AKL*DF*kb3*LpAK*LpAKL + DF*kb2*LK*LpAK*LpAKL + DF*kcat1*LK*LpAK*LpAKL - K*kb2*LpAKL^2 + AK*kb3*LpAKL^2 - K*kcat1*LpAKL^2 - DF*kcat7*LK*LpAK*LpAPLp + K*kcat7*LpAKL*LpAPLp - DF*kcat7*LK*LpAK*LpP + K*kcat7*LpAKL*LpP 
    dL*(-(DF*L*LpAK) + Km1*LpAKL) = AKL^2*DF*ka2*Km1*Lp - AK*AKL*DF*ka2*L*Lp + AKL*DF*ka3*Km1*LK*LpA - AK*DF*ka3*L*LK*LpA - AKL*DF*kb3*L*LpAK + AKL*DF*kcat1*L*LpAK - APLp*DF*kcat7*L*LpAK + A*DF*ka3*L*LK*LpAK + DF*kcat1*L*LK*LpAK - AKL*DF^2*ka2*L*Lp*LpAK - AKL*kb2*Km1*LpAKL - AKL*kcat1*Km1*LpAKL + APLp*kcat7*Km1*LpAKL + AK*kb2*L*LpAKL + AK*kb3*L*LpAKL - A*ka3*Km1*LK*LpAKL - kcat1*Km1*LK*LpAKL + AKL*DF*ka2*Km1*Lp*LpAKL + DF*kb2*L*LpAK*LpAKL + DF*kcat1*L*LpAK*LpAKL - kb2*Km1*LpAKL^2 - kcat1*Km1*LpAKL^2 - DF*kcat7*L*LpAK*LpAPLp + kcat7*Km1*LpAKL*LpAPLp - DF*kcat7*L*LpAK*LpP + kcat7*Km1*LpAKL*LpP 
    Km1*(-(AKL*DF*ka2*LK*Lp) - DF*ka3*LK^2*LpA + AKL*kb3*LpAKL - A*ka3*LK*LpAKL + kb2*LK*LpAKL + kb3*LK*LpAKL - DF*ka3*LK*LpA*LpAKL + kb3*LpAKL^2) = L*(-(AKL*DF*K*ka2*Lp) - DF*K*ka3*LK*LpA + AKL*DF*kb3*LpAK - A*DF*ka3*LK*LpAK - DF^2*ka3*LK*LpA*LpAK + K*kb2*LpAKL + K*kb3*LpAKL + DF*kb3*LpAK*LpAKL)
=#

#parameter list with experimental values
"""Km1, kcat1, ka2, kb2, ka3, kb3, ka4, kb4, ka7, kb7, kcat7, DF"""
#Unknown values marked with 0.0
function makePsym(kcat1::Float64, ka4::Float64, ka7::Float64, DF::Float64)
    return [:Km1 => 15.0, :kcat1 => kcat1, :ka2 => 0.7*10^-3, :kb2 => 2.0*10^-3,
        :ka3 => 0.118, :kb3 => 0.0609, :ka4 => ka4, :kb4 => 29.0 * ka4, :ka7 => ka7, 
        :kb7 => 39.0 * ka7 - 85.3, :kcat7 => 85.3, :df => DF]
 end
 psym = makePsym(0.1,0.2,0.3,0.4)
 p = [x[2] for x in psym]

#? Initial condition list
usym = [:L => 5.0, :K => 0.5, :P => 0.3, :A => 2.0, :Lp => 0.0, :LpA => 0.0, :LK => 0.0, 
        :LpP => 0.0, :LpAK => 0.0, :LpAP => 0.0, :LpAKL => 0.0, :LpAPLp => 0.0, :AK => 0.0, :AP => 0.0, 
        :AKL => 0.0, :APLp => 0.0]
u0 = [x[2] for x in usym]


#? Timespan for integration
tspan = (0., 100.)

odeprob = ODEProblem(eliminationSystem!, u0, tspan, p)

#Validation against the system with no Michaelis-Menten approximations
include("../UTILITIES/ODESystems.jl")

inplaceprobfull = ODEProblem(fullmodel_ode!, u0, tspan, p)

pMM = zeros(12)
Km1 = sum(p[2:3])/p[1]
pMM[1] = Km1
pMM[2:12] = p[3:13]
inplaceprobMM = ODEProblem(eliminationSystem!,u0,tspan,pMM)
import Plots
usym = [:L => 10^1.6,  :K => 10^0.8, :P => 10^0.6, :A => 10^1.2,:Lp => 0.0, :LpA => 0.0, :LK => 0.1, 
        :LpP => 0.0, :LpAK => 0.0, :LpAP => 0.0, :LpAKL => 0.0, :LpAPLp => 0.0 ]
# u0[1] = 3
# u0[5] = 0
u0=[i[2] for i in usym]
solfull = solve(inplaceprobfull)
solMM = solve(inplaceprobMM)
Plots.plot(solfull)
Plots.plot(solMM)